UniShed/UniShed/urls.py
from django.contrib import admin
from login_user import views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('user/', include('login_user.urls')),
    path('schedule/', include('schedule.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = "UNISHED Администрирование"
admin.site.site_title = "UNISHED База Данных"
admin.site.index_title = "Система Базы Данных UNISHED"

UniShed/login_user/urls.py
from django.urls import path
from . import views

#TEMPLATE URLS!
app_name = 'login_user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
]

UniShed/schedule/urls.py
from django.urls import path
from . import views

#TEMPLATE URLS!
from .views import CourseScheduleView

app_name = 'schedule'


urlpatterns = [
    path('s_schedule/', views.student_schedule_view, name='student_schedule'),
    path('l_schedule/', views.lector_schedule_view, name='lector_schedule'),
    path('dispatcher/', views.dispatcher_view, name="dispatcher_view"),
    path('sort_group/', views.sort_schedule, name="sort_schedule_view"),
    path("table/", CourseScheduleView.as_view()),
    path('busy_auditoriums/', views.busy_auditoriums_view, name="busy_auditoriums"),
    path('busy_lectors/', views.busy_lectors_view, name="busy_lectors"),
]

UniShed/login_user/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _


class UserProfileInfo(models.Model): #this class inherit from models.Model
    class Meta:
        verbose_name_plural = _('Информация о пользователях UNISHED')

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile") #that's extending the class oneToOne -relationship, field with the user itself
    #the reason for that is because this is a Model class to add an additional information that the defaultuser doesn't have

    #additional
    middle_name = models.CharField(max_length=30, verbose_name=_("Отчество"))
    birth_date = models.DateField(null=True, blank=True, verbose_name=_("Дата рождения"))
    phone = PhoneNumberField(null=True, blank=True, unique=True, verbose_name=_("Телефон"))

    def __str__(self):
        return self.user.last_name

    def get_user_type(self):
        if hasattr(self, 'student'):
            return 'student'
        elif hasattr(self, 'lector'):
            return 'lector'

UniShed/login_user/forms.py
import datetime
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from .models import UserProfileInfo
from phonenumber_field.formfields import PhoneNumberField
from bootstrap_datepicker_plus import DatePickerInput
from django.utils.translation import gettext_lazy as _


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label=_("Пароль"))
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label=_("Повторить  пароль"))

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Пароли не совпадают"
            )

class UserProfileInfoForm(forms.ModelForm):
    phone = PhoneNumberField(label=_("Телефон"))
    birth_date = forms.DateField(
        widget=DatePickerInput(
            options={'locale': settings.LANGUAGE_CODE,
                     'minDate': str(datetime.date.today() - datetime.timedelta(days=settings.MIN_BIRTH_DATE)),
                     'maxDate': str(datetime.date.today() - datetime.timedelta(days=settings.MAX_BIRTH_DATE)),
                     },
            format=settings.DATE_INPUT_FORMATS,
        ),
        label=_("Дата рождения")
    )

    class Meta():
        model = UserProfileInfo
        fields = ('middle_name', 'birth_date', 'phone')

UniShed/login_user/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'login_user/index.html')


def special(request):
    return HttpResponseRedirect("You're logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save() #we are grabbing the user form and save it
            user.set_password(user.password) #we are hasing the password and save it
            user.save() #we save those changes to the user

            profile = profile_form.save(commit=False) #I don't want to commit to the database, otherwise I may get errors with collisions. Instead we use one to one relationship
            profile.user = user #onetoone relationship is defined in the views.py file

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'login_user/registration.html',
                            {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("АККАУНТ НЕ АКТИВЕН!")

        else:
            print("Кто-то пытался войти в систему, но не удалось!")
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("Предоставлены неверные данные для входа")

    else:
        return render(request, 'login_user/login.html')

UniShed/templates/login_user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="UTF-8">
        <title>UNISHED </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        {% load bootstrap4 %}
        {% bootstrap_css %}

        {% bootstrap_javascript  jquery='full' %}

        <script src="https://kit.fontawesome.com/38b20078fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mynav">
        <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">UNISHED</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    {% if user.is_authenticated or user.is_registered %}
                        {% if user.profile.get_user_type == 'student' %}
                            <li>
                                <a class="nav-link" href="{% url 'schedule:student_schedule' %}">Расписание Студента</a>
                            </li>
                        {% elif user.profile.get_user_type == 'lector' %}
                            <li>
                                <a class="nav-link" href="{% url 'schedule:lector_schedule' %}">Расписание Преподавателя</a>
                            </li>
                            {% elif user.is_staff %}
                            <li>
                                <a class="nav-link" href="{% url 'schedule:dispatcher_view' %}">Расписание</a>

                            </li>
                            <li> <a class="nav-link" href="{% url 'admin:index' %}">База Данных</a></li>
                        {% endif %}
                        <li>
                            <a class="nav-link" href="{% url 'logout' %}"  >Выйти</a>
                        </li>
                    {% else %}
                         <li class="nav-link">
                            <a href="{% url 'login_user:register' %}" class="nav-link">Регистрация</a>
                        </li>
                        <li class="nav-link">
                            <a href="{% url 'login_user:user_login' %}" class="nav-link">Войти</a>
                        </li>

                    {% endif %}

                </ul>
            </div>
        </div>

    </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% block javascript %}
        <script src="{% static 'js/schedule.js' %}"></script>
    {% endblock %}
    </body>
</html>

UniShed/templates/login_user/index.html
{% extends "login_user/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Добро пожаловать</h1>
    <h2> В электронную систему расписания КНИТУ(Корпус У)</h2>
</div>
{% endblock %}

{% block javascript %}

{% endblock %}

UniShed/templates/login_user/login.html
{% extends 'login_user/base.html' %}
{% load static %}
{% block body_block %}

    <div class="jumbotron">
        <h2>Пожалуйста Войдите в Систему</h2>
        <form action="{% url 'login_user:user_login' %}" method="post">
            {% csrf_token %}
            <p>
            <label for="username"> Логин:</label>
            <input type="text" name="username" placeholder="Введите логин">
            </p>
            <p>
            <label for="password"> Пароль:</label>
            <input type="text" name="password" placeholder="Введите пароль:">
            </p>
            <p>
            <input type="submit" value="Войти">
            </p>
        </form>

    </div>

{% endblock %}

UniShed/templates/login_user/registration.html
{% extends 'login_user/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {%if registered %}
        <h2>Спасибо за регистрацию!</h2>
    {%else%}
        <div class="col-md-9">
            <div class="panel with-nav-tabs panel-default">
                <div class="panel-heading d-flex flex-row mb-3">
                        <ul class="nav nav-tabs">
                            <li class="nav-item p-1">
                                <a class="nav-link active" href="#tab1default" data-toggle="tab">Студент</a>
                            </li>
                            <li class="nav-item p-1">
                                <a class="nav-link " href="#tab2default" data-toggle="tab">Преподаватель</a></li>
                            <li class="nav-item dropdown p-1">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button"
                                   aria-haspopup="true" aria-expanded="false">Сотрудник </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#tab3default" data-toggle="tab">Кафедры</a>
                                    <a class="dropdown-item" href="#tab4default" data-toggle="tab">Другой сотрудник</a>
                                </div>
                            </li>
                        </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade-in active" id="tab1default">
                            <h2>Регистрация студента</h2>
                            <form method="POST">
                                <div class="row">
                               {% csrf_token %}
                                {{ user_form.non_field_errors }}
                                {{ user_form.source.errors }}
                                {{ user_form.source }}
                                {% if user_form.subject.errors %}
                                    <ol>
                                    {% for error in user_form.subject.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                    </ol>
                                {% endif %}
                                            <div class="d-flex flex-row">
                                                <div class="p-1">
                                                    <p>
                                                        {{ user_form.last_name.label_tag }}
                                                        {{ user_form.last_name }}</p>
                                                    <p> {{ user_form.last_name.errors }} </p>
                                                </div>
                                            </div>
                                            <div class="d-flex flex-row">
                                                <div class="p-1">
                                                    <p>
                                                        {{ user_form.first_name.label_tag }}
                                                        {{ user_form.first_name }}</p>
                                                    <p> {{ user_form.first_name.errors }} </p>
                                                </div>

                                            </div>
                                            <div class="d-flex flex-row">
                                                <div class="p-1">
                                                    <p>
                                                        {{ profile_form.middle_name.label_tag }}
                                                        {{ profile_form.middle_name }}</p>
                                                    <p> {{ profile_form.middle_name.errors }} </p>
                                                </div>

                                            </div>
                                        <div class="d-flex flex-row ">
                                            <div class="p-1 ">
                                                <p>
                                                    {{ user_form.username.label_tag }}
                                                    {{ user_form.username }}</p>
                                                <p> {{ user_form.username.errors }} </p>
                                            </div>
                                            <div class="p-1 ">
                                                <p>
                                                    {{ user_form.password.label_tag }}
                                                    {{ user_form.password }}</p>
                                                <p> {{ user_form.password.errors }} </p>
                                            </div>
                                            <div class="p-1 ">
                                                <p>
                                                    {{ user_form.confirm_password.label_tag }}
                                                    {{ user_form.confirm_password }}</p>
                                                <p> {{ user_form.confirm_password.errors }} </p>
                                            </div>
                                        </div>
                                    <div class="d-flex flex-column ">
                                            <div class="p-1">
                                                <p>
                                                    {{ profile_form.birth_date.label_tag }}
                                                    {{ profile_form.birth_date}}</p>
                                                <p> {{ profile_form.birth_date.errors }} </p>
                                            </div>
                                        </div>
                                        <div class="d-flex flex-row ">
                                                <div class="p-1">
                                                    <p>
                                                        {{ profile_form.phone.label_tag }}
                                                        {{ profile_form.phone }}</p>
                                                    <p> {{ profile_form.phone.errors }} </p>
                                                </div>
                                            </div>
                                    <div class="d-flex flex-row ">
                                        <div class="p-1">
                                            <p>
                                                {{ user_form.email.label_tag }}
                                                {{ user_form.email }}</p>
                                            <p> {{ user_form.email.errors }} </p>
                                        </div>
                                    </div>
                                </div>
                                <input type="submit" name="" value="Регистрация">
                                {{ profile_form.media }}
                            </form>
                        </div>
                        <div class="tab-pane fade" id="tab2default">
                            <h2>Регистрация преподавателя</h2>
                            <form method="POST">
                                {% csrf_token %}
                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}
                                {{profile_form.media}}
                                <input type="submit" name="" value="Регистрация">
                            </form>
                        </div>
                        <div class="tab-pane fade" id="tab3default">
                            <h2>Регистрация сотрудника кафедры</h2>
                            <form method="POST">
                                {% csrf_token %}
                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}
                                {{profile_form.media}}
                                <input type="submit" name="" value="Регистрация">
                            </form>
                        </div>
                        <div class="tab-pane fade" id="tab4default">
                            <h2>Регистрация сотрудника</h2>
                            <form method="POST">
                                {% csrf_token %}
                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}
                                {{profile_form.media}}
                                <input type="submit" name="" value="Регистрация">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {%endif%}
</div>

{%endblock%}